name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "50 15 * * 6"

jobs:
  schedule:
    name: schedule
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git fetch origin
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
      - name: Run script
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: python3 .github/scripts/schedule.py