name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "50 15 * * 6"

jobs:
  schedule:
    name: schedule
    runs-on: ubuntu-latest
    env:
      COOKIE: ${{ secrets.COOKIE }}
    steps:
      - name: Check out repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git fetch origin
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
      - name: Debug environment variables
        run: |
          echo "Checking COOKIE environment variable..."
          if [ -z "$COOKIE" ]; then
            echo "❌ COOKIE is empty or not set"
          else
            echo "✅ COOKIE is set (length: ${#COOKIE})"
          fi
          echo "All environment variables starting with 'C':"
          env | grep "^C" || echo "None found"
      - name: Run script
        run: python3 .github/scripts/schedule.py